-- CreateTable
CREATE TABLE "RunLog" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "patchRulesetVersion" TEXT NOT NULL DEFAULT '',
    "routeVersion" TEXT NOT NULL DEFAULT '',
    "purpose" TEXT NOT NULL DEFAULT 'PB',
    "testVariable" TEXT NOT NULL DEFAULT '',
    "controlCondition" TEXT NOT NULL DEFAULT '',
    "executionGrade" TEXT NOT NULL DEFAULT 'B',
    "finalTime" TEXT NOT NULL DEFAULT '',
    "result" TEXT NOT NULL DEFAULT 'Completion',
    "resetPointCause" TEXT NOT NULL DEFAULT '',
    "weapon" TEXT NOT NULL DEFAULT '',
    "packTimingLevel" TEXT NOT NULL DEFAULT '',
    "perks" TEXT NOT NULL DEFAULT '',
    "armorPurchased" BOOLEAN NOT NULL DEFAULT false,
    "gobbleGumsUsed" TEXT NOT NULL DEFAULT '',
    "s2Power" TEXT NOT NULL DEFAULT '',
    "s3FirstObjectiveStart" TEXT NOT NULL DEFAULT '',
    "s4FirstObjectiveComplete" TEXT NOT NULL DEFAULT '',
    "s5FirstPack" TEXT NOT NULL DEFAULT '',
    "s6FinalRequiredItem" TEXT NOT NULL DEFAULT '',
    "s7BossEntry" TEXT NOT NULL DEFAULT '',
    "s8FirstRam" TEXT NOT NULL DEFAULT '',
    "bossCycleTimes" TEXT NOT NULL DEFAULT '',
    "largestSplitGain" TEXT NOT NULL DEFAULT '',
    "largestSplitLoss" TEXT NOT NULL DEFAULT '',
    "pointTotalsS5S6S7" TEXT NOT NULL DEFAULT '',
    "ammoStateAtS7" TEXT NOT NULL DEFAULT '',
    "mistakes" TEXT NOT NULL DEFAULT '',
    "resetWorthyMistake" BOOLEAN NOT NULL DEFAULT false,
    "validEvidenceReason" TEXT NOT NULL DEFAULT '',
    "nextTest" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "RunLog_pkey" PRIMARY KEY ("id")
);
